### PR TITLE
Add scheduled headways to bus events

### PR DESCRIPTION
**Pull request by hamima-halim**
Adding scheduled headways and timetables to bus events as per https://github.com/transitmatters/gobble/issues/3.

Nothing fancy, except that I've set the headway for the first stop of a trip to -1. Can also make that 0 or NaN y'all prefer.

### CODE REVIEW

**Review by mathcolo — APPROVED** [review]
AMAZING I AM SO GLAD YOU'RE HERE YESSSSSS

Can the first be empty string?
```
$ aws s3 cp s3://tm-mbta-performance/Events/monthly-bus-data/66-0-1378/Year=2023/Month=6/events.csv.gz - | zcat | head -n 2
service_date,route_id,trip_id,direction_id,stop_id,stop_sequence,vehicle_id,vehicle_label,event_type,event_time,scheduled_headway,scheduled_tt
2023-06-01,66,59647325.0,0,1378,6,,,ARR,2023-06-01 05:02:36,,840.0
```

**Comment by hamima-halim** [comment]
> AMAZING I AM SO GLAD YOU'RE HERE YESSSSSS
> 
> Can the first be empty string?
> 
> ```
> $ aws s3 cp s3://tm-mbta-performance/Events/monthly-bus-data/66-0-1378/Year=2023/Month=6/events.csv.gz - | zcat | head -n 2
> service_date,route_id,trip_id,direction_id,stop_id,stop_sequence,vehicle_id,vehicle_label,event_type,event_time,scheduled_headway,scheduled_tt
> 2023-06-01,66,59647325.0,0,1378,6,,,ARR,2023-06-01 05:02:36,,840.0
> ```

Ofc!! 
To clarify, does this mean that you'd like me to remove the initial header row from the daily bus event logs?

**Comment by mathcolo** [comment]
Oh, sorry, no—I mean can the scheduled headway for the first trip of the day be empty string? I _think_ that's what the system is expecting

**Comment by hamima-halim** [comment]
> Oh, sorry, no—I mean can the scheduled headway for the first trip of the day be empty string? I _think_ that's what the system is expecting

oh sweet, done 👍

**Pull request merged**
